#logging:
#  level:
#    com.bizzjen.cipes: INFO

server:
  port: 8081

spring:
  application:
    name: CIPES-APP

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/